version: '3.8'

services:
  db:
    image: postgres:17.2
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: reportbotdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    

  bot:
    build: ./
    restart: always
    stop_signal: SIGINT
    depends_on:
      - db
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DSN: ${DSN}
      ADMIN_IDS: ${ADMIN_IDS}
      TABLE_NAME: ${TABLE_NAME}
    volumes:
      - .:/app
    working_dir: /app

volumes:
  pgdata:
